application: ems
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: LoginFinal.app
- url: /welcome.*
  script: Welcome.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest