application: emswithguii
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /files
  static_dir: files

- url: /.*
  script: LoginFinal.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
